# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    string_decorator.class: AppBundle\Twig\AppExtension

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    twig.string_decorator:
        class: %string_decorator.class%
        tags:
            - { name: twig.extension }
